name: BlockShuffle
version: 1.0-SNAPSHOT
main: me.pzdrs.blockshuffle.BlockShuffle
api-version: 1.13
authors: [Pzdrs]
description: Inspired by Dream
commands:
  blockShuffle:
    description: Main command
    usage: /<command> <start | stop>
    aliases:
      - bs
