name: Bingo
version: 0.4
main: me.pzdrs.bingo.Bingo
api-version: 1.16
authors: [Pzdrs]
description: A Bingo minigame

commands:
  bingo:
    usage: /<command> [subcommand] [player]
    description: The main command
    aliases:
      - b